theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: encommuns.net
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo-avatar.svg"
  summary:
    position: hero
  breadcrumb:
    position: none
  search:
    active: true
  persons:
    single:
      backlinks: true
  posts:
    index:
      layout: grid
      truncate_description: 0
