theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  breadcrumb:
    position: none
  search:
    active: true
  persons:
    single:
      backlinks: true
  posts:
    index:
      truncate_description: 0
